// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdaroConnect.Application.AppConsole.Entities;

public partial class CostCenter
{
    public Guid Id { get; set; }

    public int? TenantId { get; set; }

    public string CostCenterCode { get; set; }

    public string ControllingArea { get; set; }

    public string CostCenterShort { get; set; }

    public string CostCenterName { get; set; }

    public string DepartmentName { get; set; }

    public string Description { get; set; }

    public string ActState { get; set; }

    public bool? IsActive { get; set; }

    public string Period { get; set; }

    public virtual ICollection<GeneralLedgerAccount> GeneralLedgerAccounts { get; set; } = new List<GeneralLedgerAccount>();
}