// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdaroConnect.Application.AppConsole.Entities;

public partial class Ekko
{
    public Guid Id { get; set; }

    public int? TenantId { get; set; }

    public string Mandt { get; set; }

    public string Ebeln { get; set; }

    public string Bukrs { get; set; }

    public string Bstyp { get; set; }

    public string Bsart { get; set; }

    public string Bsakz { get; set; }

    public string Loekz { get; set; }

    public string Statu { get; set; }

    public DateTime? Aedat { get; set; }

    public string Ernam { get; set; }

    public long? Pincr { get; set; }

    public long? Lponr { get; set; }

    public string Lifnr { get; set; }

    public string Zterm { get; set; }

    public decimal? Zbd1t { get; set; }

    public decimal? Zbd2t { get; set; }

    public decimal? Zbd3t { get; set; }

    public decimal? Zbd1p { get; set; }

    public decimal? Zbd2p { get; set; }

    public string Ekorg { get; set; }

    public string Ekgrp { get; set; }

    public string Waers { get; set; }

    public decimal? Wkurs { get; set; }

    public string Kufix { get; set; }

    public DateTime? Bedat { get; set; }

    public DateTime? Kdatb { get; set; }

    public DateTime? Kdate { get; set; }

    public DateTime? Bwbdt { get; set; }

    public DateTime? Gwldt { get; set; }

    public DateTime? Ihran { get; set; }

    public string Kunnr { get; set; }

    public string Konnr { get; set; }

    public string Abgru { get; set; }

    public string Autlf { get; set; }

    public string Weakt { get; set; }

    public string Reswk { get; set; }

    public string Lblif { get; set; }

    public string Inco1 { get; set; }

    public string Inco2 { get; set; }

    public string Submi { get; set; }

    public string Knumv { get; set; }

    public string Kalsm { get; set; }

    public string Procstat { get; set; }

    public string Unsez { get; set; }

    public string Frggr { get; set; }

    public string Frgsx { get; set; }

    public string Frgke { get; set; }

    public string Frgzu { get; set; }

    public string Adrnr { get; set; }
}