// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdaroConnect.Application.AppConsole.Entities;

public partial class Ekpo
{
    public Guid Id { get; set; }

    public int? TenantId { get; set; }

    public string Mandt { get; set; }

    public string Ebeln { get; set; }

    public long? Ebelp { get; set; }

    public string Uniqueid { get; set; }

    public string Loekz { get; set; }

    public string Statu { get; set; }

    public DateTime? Aedat { get; set; }

    public string Txz01 { get; set; }

    public string Matnr { get; set; }

    public string Ematn { get; set; }

    public string Bukrs { get; set; }

    public string Werks { get; set; }

    public string Lgort { get; set; }

    public string Bednr { get; set; }

    public string Matkl { get; set; }

    public string Infnr { get; set; }

    public string Idnlf { get; set; }

    public long? Ktmng { get; set; }

    public long? Menge { get; set; }

    public string Meins { get; set; }

    public string Bprme { get; set; }

    public decimal? Bpumz { get; set; }

    public decimal? Bpumn { get; set; }

    public decimal? Umrez { get; set; }

    public decimal? Umren { get; set; }

    public decimal? Netpr { get; set; }

    public decimal? Peinh { get; set; }

    public decimal? Netwr { get; set; }

    public decimal? Brtwr { get; set; }

    public DateTime? Agdat { get; set; }

    public decimal? Webaz { get; set; }

    public string Mwskz { get; set; }

    public string Bonus { get; set; }

    public string Insmk { get; set; }

    public string Spinf { get; set; }

    public string Prsdr { get; set; }

    public string Bwtar { get; set; }

    public string Bwtty { get; set; }

    public string Abskz { get; set; }

    public string Pstyp { get; set; }

    public string Knttp { get; set; }

    public string Konnr { get; set; }

    public long? Ktpnr { get; set; }

    public decimal? Packno { get; set; }

    public string Anfnr { get; set; }

    public string Banfn { get; set; }

    public long? Bnfpo { get; set; }
}