// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Ganss.Excel;

namespace AdaroConnect.Application.AppConsole.Entities;

public partial class Zmm021r
{
    public Guid Id { get; set; }

    public int? TenantId { get; set; }

    public string PurchasingDocument { get; set; }
    public string PurchasingDocType { get; set; }
    public string PurchasingDocTypeDescription { get; set; }
    public string Item { get; set; }
    public string LineNumber { get; set; }
    public string DeletionIndicator { get; set; }

    public DateTime? DocumentDate { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string PurchaseRequisition { get; set; }

    public string ItemPr { get; set; }

    public string SupplierCode { get; set; }

    public string SupplierName { get; set; }

    public string Address { get; set; }

    public string ItemNo { get; set; }

    public string MaterialGroup { get; set; }

    public string ShortText { get; set; }

    public double? OrderQuantity { get; set; }

    public string OrderUnit { get; set; }

    public string Currency { get; set; }

    public DateTime? DeliveryDate { get; set; }

    public double? NetPrice { get; set; }

    public double? NetOrderValue { get; set; }

    public double? Demurrage { get; set; }

    public double? GrossPrice { get; set; }

    public double? TotalDiscount { get; set; }

    public double? FreightCost { get; set; }

    public string ReleaseIndicator { get; set; }

    public string Plant { get; set; }

    public string PurchasingGroup { get; set; }

    public string TaxCode { get; set; }

    public string CollectiveNumber { get; set; }

    public string ItemCategory { get; set; }

    public string AccountAssignment { get; set; }

    public string OutlineAgreement { get; set; }

    public string Rfqno { get; set; }

    public double? QtyPending { get; set; }

    public string MaterialService { get; set; }

    public string ApprovalStatus { get; set; }

    public string Postatus { get; set; }

    public string Period { get; set; }

    public string CommentVendor { get; set; }

    public string ItemText { get; set; }

    public string LongText { get; set; }

    public string OurReference { get; set; }

    public DateTime? PrfinalFirstApprovalDate { get; set; }

    public DateTime? PrfinalLastApprovalDate { get; set; }

    public DateTime? PofirstApprovalDate { get; set; }

    public DateTime? PolastApprovalDate { get; set; }

    public string PoapprovalName { get; set; }

    public string BuyerCode { get; set; }

    public string BuyerName { get; set; }

    public string Picdept { get; set; }

    public string Picsect { get; set; }

    public string FuelAllocation { get; set; }

    public string CostCenter { get; set; }

    public string CostCenterDescription { get; set; }

    public string Wbselement { get; set; }

    public string AssetNo { get; set; }

    public string FundCenter { get; set; }
}
